### PR TITLE
Allow query integration while indexing because we have versioning.

### PR DESCRIPTION
**Pull request by rebeccahum**
## Description
Do not disable query integration during indexing, as we have versioning in place.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] This change has the fix PRed upstream (if applicable). If not applicable, it has the relevant "// VIP: reason for the discrepancy with upstream" comment in places where the code is discrepant.

### CODE REVIEW

**Review by pschoffer — CHANGES_REQUESTED** [review]
Looks good overall. But I think maybe we could introduce a filter instead? Something along the lines of `ep_wp_disconnect_query_integration_on_full_index` with default true.

That way, we could upstream it as well. That would maybe akes sense for some other usecases even if they don't have versioning. I think that some sites my choose to search on incomplete index rather than take a chance with slow DB.

What do you think?

**Comment by rebeccahum** [comment]
Yep, that's what I'm currently doing upstream actually but I pinged you too early to review 🤦

**Comment by rebeccahum** [comment]
Upstream PR: https://github.com/10up/ElasticPress/pull/3445

**Review by pschoffer — APPROVED** [review]
Incredible, this is very clean! I saw upstream is already merged too.

**Pull request merged**
