### PR TITLE
Pull/3.6.4

### PR DESCRIPTION
**Pull request by pschoffer**
### Description of the Change

Pulls https://github.com/10up/ElasticPress/releases/tag/3.6.4 and https://github.com/10up/ElasticPress/releases/tag/3.6.3 

### Follow up:

* https://vipjira.atlassian.net/browse/CANTINA-799 - we had a workaround we can address now using filter
* https://vipjira.atlassian.net/browse/CANTINA-800 - admin notice workaround can be removed probably
* https://vipjira.atlassian.net/browse/CANTINA-801 - unit test fix

### Testing
* I went through both changelogs, nothing popped out.
* I tested search, reindexing of posts/users/terms and some basic changes to be automatically synced to ES.

### CODE REVIEW

**Comment by rebeccahum** [comment]
@pschoffer I'm seeing that the below unit test is failing now:
```
1) ElasticPressTest\TestComment::testCommentQueryOffset
Failed asserting that false is true.
```
We should fix that before proceeding. The culprit seems to be from https://github.com/Automattic/ElasticPress/commit/93bd73c534db6f57f0b2000f40990288d2b7c273 and use of offsets
https://github.com/Automattic/ElasticPress/blob/77907388b1b5473dc1070f8dce7e59bd2a0f43f7/includes/classes/Indexable.php#L358-L365

I've opened https://github.com/Automattic/ElasticPress/pull/130 to resolve the issue.

**Comment by pschoffer** [comment]
@rebeccahum this test was failing before as well. This is why it is commented out in develop now.

as part of this merge, I uncommented it (because there was a change in it) hoping it is fixed now. But it is not. So I created https://vipjira.atlassian.net/browse/CANTINA-801 as per PR description.

I'll try to have a look today though.

**Comment by pschoffer** [comment]
@rebeccahum you were right about pinpointing the root cause. The test is fixed now.

**Comment by pschoffer** [comment]
@rebeccahum I reverted the change to get the test pass. Now with your fix in place it is no longer needed.

**Comment by rebeccahum** [comment]
Did some testing and it seems to be functioning as expected.

**Review by rebeccahum — APPROVED** [review]

**Pull request merged**
