### PR TITLE
Combine date term preparation during bulk post indexing

### PR DESCRIPTION
**Pull request by WPprodigy**
## Performance Problem

This one surprised me. During testing on the `sw-test` environment, I was trying to nail down where an extra ~8 seconds was coming from per set of 500 posts being indexed. I added manual logging everywhere that seemed likely it could be a culprit, but looked over this spot every time. Guess the meme is true about trying to make performance adjustments before profiling 😆

Eventually set up cachegrind, and here we are:
before

There are 4 calls to prepare_date_terms() per post being indexed. Each call resulted in 12 calls to `date_i18n()`, which ends up going down a bit of a rabbit hole and eventually adding up to a lot of time spent doing filters and alloption calls. So per page of 500 posts being indexed, that is 24,000 calls (500 x 12*4)- seen in the cachegrind graph above.

**Before the changes**, a test group of 500 posts took 7.91601 seconds running prepare_date(). **After this PR**, 0.85888 seconds.

## Solution

Rather than multiple calls to `date_i18n()` for individual date formats - we can just make one call with all the formats we are after. Using `||` as a separator, can then extract out the individual pieces we need to index. From 24,000 calls to 2000. 

Did a bit of extra refactoring to the method to ensure that future changes to `$terms_to_prepare` can be made easily and without an accidental index-counting problem.

## Testing

On a few other sites I tried, the large time sunk was not as replicable. I believe it has to do with timezone setting differences, or rather how the `sw-test` environment has some empty timezone options. All in all though, this patch is quite minimal and offers improvements no matter what.

The quickest way to test would be to just make the `prepare_date_terms()` method public and ensure the outputs are the same for differing dates if you'd like:

```
$indexable = ElasticPress\Indexables::factory()->get( 'post' );
$indexable->prepare_date_terms('2020-03-24 10:42:20');
```

### CODE REVIEW

**Comment by rinatkhaziev** [comment]
Noting a failing test here:

```
There was 1 failure:
1) ElasticPressTest\TestPost::testPaginationWithOffset
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'two'
+'one'
/home/travis/build/Automattic/ElasticPress/tests/php/indexables/TestPost.php:188
```

**Comment by WPprodigy** [comment]
Call the test's bluff and just made it re-run. It's passing now. The fail seemed pretty unrelated, although maybe the performance improvement caught it off guard because indexing was too fast ;p

**Comment by WPprodigy** [comment]
Looks like this change is already quite well covered by tests: https://github.com/Automattic/ElasticPress/blob/develop/tests/php/indexables/TestPost.php#L4144-L4755. Think we're all good on that end.

**Review by rinatkhaziev — APPROVED** [review]
Looks good!

**Pull request merged**
